### ISSUE TITLE
Support for x86 architecture

### ISSUE THREAD

**Issue by VeirryAu** [nowarzz/react-native-epson-tm82#6]
Hi, thanks to support this great library for community.
But i need help to implementation to my apps.

**Problem:**
when i'm running in x86 architecture, i got this error
![Screenshot_1567999355](https://user-images.githubusercontent.com/51213555/64501524-e903d200-d2eb-11e9-9f73-41a2b68455a5.png)

**Probably cause:**
i found that jniLibs doesn't have x86 support in this library. can you tell me how i can get this x86 support ?

regards.
Thanks to your attention

**Comment by nowarzz** [comment]
Hi @VeirryAu 

I am very sorry that I miss out your issue for several months. Hoping that you have found the solution.

Unfortunately, I could only say sorry that by the time you post the issue, the ePOS SDK for Epson was on v2.12.0 which they doesn't support x86, I have checked today (10 Apr 20) that they have updated the library to v2.14.0 and in the README, they do support x86. I will try to update the libs to the updated and get back to you..

By the mean time, you probably could use generic ESC/POS solution for printing:
[https://www.npmjs.com/package/react-native-ipos-printer](url)
The libs is also written by me, but due to several reasons, I couldn't make it open source.

**Comment by nowarzz** [comment]
hi @VeirryAu 

I have tried to update to ePOS 2.14.0 to support x86 devices. Could you try #9 fix and please let me know if this solve your problems

**Comment by VeirryAu** [comment]
Hi @nowarzz 

Thanks for your hard work. But honestly, I'm not working on project that use this library at this moment. You can close this issue if you has test it yourself in your x86 emulator or device.

Although, please allow me or anyone to create a new question if about this problem in the other day if we're facing this issue again.

**Comment by VeirryAu** [comment]
This is a great library and very useful for our community, Thanks for your hardwork to support this library.

**Comment by nowarzz** [comment]
Hi @VeirryAu 

I am very sorry that I didn't respond in time. I will test it on my x86 emulator and close this issue.
